#pragma once

#include "patches/cars_dialogue_ex.hpp"
#include "patches/data_access_logging.hpp"
#include "patches/debug_txt_support.hpp"
#include "patches/dialogue_list.hpp"
#include "patches/explore_music.hpp"
#include "patches/game_text_json.hpp"
#include "patches/hdr.hpp"
#include "patches/large_vehicles.hpp"
#include "patches/loading_screen_name.hpp"
#include "patches/misc.hpp"
#include "patches/playlist_events.hpp"
#include "patches/ui_sounds_fix.hpp"
#include "patches/widescreen.hpp"