
#define AA_NONE 0
#define AA_USE_TWO_FRAME_PIXEL_OFFSET 1
#define AA_USE_ONE_FRAME_PIXEL_OFFSET_WITHOUT_AF 2
#define AA_USE_ONE_FRAME_PIXEL_OFFSET_WITH_AF 4
#define AA_USE_SIMPLE_BLUR 8
#define AA_USE_HARDWARE_2X 16
#define AA_USE_HARDWARE_4X 32

#define AA_SOLUTION AA_USE_HARDWARE_4X
